/*
 * ImageSizePanel.java
 *
 * Created on November 4, 2005, 6:49 AM
 */
package net.java.dev.imagine.ui.components;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import net.java.dev.imagine.ui.common.BackgroundStyle;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;
import org.openide.util.NbPreferences;

/**
 *
 * @author Timothy Boudreau
 */
public class ImageSizePanel extends javax.swing.JPanel {

    private Dimension imgSize = null;

    public ImageSizePanel() {
        initComponents();
        String val = NbPreferences.forModule(ImageSizePanel.class)
                .get("background", null);
        if (val != null) {
            try {
                BackgroundStyle bg = BackgroundStyle.valueOf(val);
                backgroundBox.setSelectedItem(bg);
            } catch (Exception ex) {
                Exceptions.printStackTrace(ex);
            }
        }
    }

    public ImageSizePanel(Dimension d) {
        this();
        imgSize = d;
    }

    public ImageSizePanel(boolean showTransparentBox) {
        this(showTransparentBox, null);
    }

    public ImageSizePanel(boolean showTransparentBox, Dimension size) {
        this();
        imgSize = size;
        if (!showTransparentBox) {
            backgroundBox.setVisible(false);
            backgroundLabel.setVisible(false);
        }
    }

    public boolean isTransparent() {
        return backgroundBox.getSelectedItem() == BackgroundStyle.TRANSPARENT;
    }

    public BackgroundStyle getBackgroundStyle() {
        return (BackgroundStyle) backgroundBox.getSelectedItem();
    }

    private Dimension preferredImageSize = new Dimension(640, 480);

    public Dimension getDimension() {
        Dimension result = imgSize == null ? preferredImageSize : imgSize;
        boolean bad = false;
        try {
            result.width = Integer.parseInt(jTextField1.getText().trim());
        } catch (NumberFormatException nfe) {
            bad = true;
        }
        try {
            result.height = Integer.parseInt(jTextField2.getText().trim());
        } catch (NumberFormatException nfe) {
            bad = true;
        }
        if (bad) {
            errorText.setText(NbBundle.getMessage(ImageSizePanel.class,
                    "LBL_BadInput")); //NOI18N
        } else {
            preferredImageSize = new Dimension(result);
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        errorText = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        org.openide.awt.Mnemonics.setLocalizedText(backgroundLabel, org.openide.util.NbBundle.getMessage(ImageSizePanel.class, "LBL_Background")); // NOI18N
        backgroundBox = new javax.swing.JComboBox<>();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ImageSizePanel.class, "LBL_Size")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, javax.swing.UIManager.getDefaults().getColor("controlShadow")));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ImageSizePanel.class, "LBL_Width")); // NOI18N

        jTextField1.setText("640");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldKeyPressed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ImageSizePanel.class, "LBL_Height")); // NOI18N

        jTextField2.setText("480");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldFocusGained(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldKeyPressed(evt);
            }
        });

        errorText.setForeground(java.awt.Color.red);

        backgroundLabel.setLabelFor(backgroundBox);
        org.openide.awt.Mnemonics.setLocalizedText(backgroundLabel, "Background");

        backgroundBox.setModel(BackgroundStyle.model() );
        backgroundBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(backgroundLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(backgroundBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 206, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(errorText, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        layout.linkSize(new java.awt.Component[] {backgroundBox, jTextField1, jTextField2}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(errorText)
                        .add(25, 25, 25))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(backgroundBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(backgroundLabel))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_fieldKeyTyped

    private void fieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldFocusGained
        JTextField jtf = (JTextField) evt.getComponent();
        jtf.setSelectionStart(0);
        jtf.setSelectionEnd(jtf.getText().length());
    }//GEN-LAST:event_fieldFocusGained

    private void fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKeyPressed

        int cd = evt.getKeyCode();
        switch (cd) {
            case KeyEvent.VK_0:
            case KeyEvent.VK_1:
            case KeyEvent.VK_2:
            case KeyEvent.VK_3:
            case KeyEvent.VK_4:
            case KeyEvent.VK_5:
            case KeyEvent.VK_6:
            case KeyEvent.VK_7:
            case KeyEvent.VK_8:
            case KeyEvent.VK_9:
            case KeyEvent.VK_RIGHT:
            case KeyEvent.VK_SHIFT:
            case KeyEvent.VK_END:
            case KeyEvent.VK_HOME:
            case KeyEvent.VK_LEFT:
            case KeyEvent.VK_TAB:
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                JRootPane root = getRootPane();
                if (root != null) {
                    JButton jb = root.getDefaultButton();
                    if (jb != null) {
                        jb.doClick();
                    }
                }
            default:
                evt.consume();
        }
    }//GEN-LAST:event_fieldKeyPressed

    private void backgroundBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundBoxActionPerformed
        if (isShowing()) {
            NbPreferences.forModule(ImageSizePanel.class)
                    .put("background", ((BackgroundStyle) backgroundBox.getSelectedItem()).name());
        }
    }//GEN-LAST:event_backgroundBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<BackgroundStyle> backgroundBox;
    public javax.swing.JLabel backgroundLabel;
    public javax.swing.JLabel errorText;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
